### ISSUE TITLE
size mismatch for classifier

### ISSUE THREAD

**Issue by asifdadra** [BDBC-KG-NLP/TEN_EMNLP2020#1]
Hello, First I would like to appreciate your work in the Domain of DST that you have been done great in TEN article. I am working on your proposed model to understand the code according to published article. I am able to reproduce results on DSTC2 dataset but when i change dataset from DSTC2 to Woz or Multiwoz in config.py  , then i am getting the following error:
File "/home/asifdadra/Downloads/enter/envs/ttp37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 847, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Model:
	size mismatch for emb_fixed.weight: copying a param with shape torch.Size([1621, 400]) from checkpoint, the shape in current model is torch.Size([950, 400]).
	size mismatch for classifier.area.weight: copying a param with shape torch.Size([7, 50]) from checkpoint, the shape in current model is torch.Size([8, 50]).
	size mismatch for classifier.area.bias: copying a param with shape torch.Size([7]) from checkpoint, the shape in current model is torch.Size([8]).
	size mismatch for classifier.food.weight: copying a param with shape torch.Size([76, 50]) from checkpoint, the shape in current model is torch.Size([77, 50]).
	size mismatch for classifier.food.bias: copying a param with shape torch.Size([76]) from checkpoint, the shape in current model is torch.Size([77]).

Process finished with exit code 1

Could you please provide your feedback to resolve this. Thank You.

**Comment by AlbertChen1991** [comment]
It seems that the errors you have mentioned are caused by loading a wrong saved model. Note that the TEN model is initialized by a TEN-X model, so when you change to another dataset, you should not only change the args['data_dir'] argument, but also the args['resume'] argument which indicates the directory where the TEN-X model is saved. Maybe you have loaded a TEN-X model on the DSTC2 dataset when you train a TEN model on the WOZ dataset, which leads to the mismatching of parameter dimensions in your created model and loaded model.

**Comment by asifdadra** [comment]
Actually, i am just training TEN-X model, i did not went to TEN. By default in config file the args['resume'] is none for Ten-X. you are right that when i changed dataset then it was loading the last saved model from directory which might be causing to lead mismatching dimensions parameters. now i have just changed the directory from TEN-X to TEN-X/woz for woz dataset in root experimental folder i.e. args ['dexp']. its now training and working. thank you.
